language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: COMPILER=g++-9
      addons:
        apt:
          update: true
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-9
          - gcc-9
          - cmake
      install: if [[ "$COMPILER" == "g++-9" ]]; then export CXX="g++-9" CC="gcc-9"; fi
      script:
        - chmod +x libs/premake5/linux/premake5
        - libs/premake5/linux/premake5 gmake2
        - make
    - os: windows
      filter_secrets: false
      env: 
        - LABEL="windows-msvc" 
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
      script:
        - libs/premake5/windows/premake5.exe vs2017 
        - export PATH=$MSBUILD_PATH:$PATH 
        - MSBuild.exe ModernFileDialogs.sln //t:Build